export enum EmailType {
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  CONTACT_EMAIL_NOTIFICATION = 'CONTACT_EMAIL_NOTIFICATION',
  SUBSCRIPTION_CONFIRMATION = 'SUBSCRIPTION_CONFIRMATION',
  SUBSCRIPTION_CANCELLATION_REQUEST = 'SUBSCRIPTION_CANCELLATION_REQUEST',
  PURCHASE_CONFIRMATION = 'PURCHASE_CONFIRMATION',
}
