export enum EActivityType {
  PHYSICAL = 'PHYSICAL',
  MENTAL = 'MENTAL',
  SENSORY = 'SENSORY',
  SOCIAL = 'SOCIAL',
  FEEDING = 'FEEDING',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  OCCUPATIONAL = 'OCCUPATIONAL',
}
